# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

url    : "https://craftersheavenmedia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ai" # the subpath of your site, e.g. /blog

#title      : Your Awesome Website
title      : RenForge - Your Leads, Our Forge
email      : renforgemedia@gmail.com 
description: "Unlock the potential of your home improvement business with expert lead generation services tailored to help you gain new, trustworthy clients. Our robust strategies connect businesses with high-quality leads actively searching for renovation services."
#author     : Your Name
author     : Gaurav Das
# logo       : assets/img/new_logo.png #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# plugins:
#   - jekyll-sitemap

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"
